version: '3'

services:

  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
      args:
        HOST_UID: ${HOST_UID}
        HOST_GID: ${HOST_GID}
    image: "php-rr-example"
    container_name: "php-rr-example-app"
    ports:
      - 8080:8080/tcp
    working_dir: /app
    command: rr serve -c /app/rr.yaml
    volumes:
      - ./php:/app
