version: "3"

services:

  app:
    image: "demidovich/php-fpm:7.4-alpine"
    container_name: "dm-fpm74-alpine-app"
    volumes:
      - ./php:/app

  queue:
    image: "demidovich/php-fpm:7.4-alpine"
    container_name: "dm-fpm74-alpine-queue"
    volumes:
      - ./php:/app
    command: php /app/artisan queue:work

  scheduler:
    image: "demidovich/php-fpm:7.4-alpine"
    container_name: "dm-fpm74-alpine-scheduler"
    volumes:
      - ./php:/app
    command: /scripts/scheduler.sh "php /app/artisan schedule:run --verbose --no-interaction"

